name: Buildx

env:
  npmrc: |
    //npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_KEY_ACTIONS }} \ 
    @newchromantics:registry=https://npm.pkg.github.com

on:
  push:
    branches:
      - docker
    #gr: testing, but cannot have path AND branch
    #paths:
    #- '**.json'
    #tsdk: need this otherwise it will never make a package later on    
    tags:        
      - v*
  watch:
    types: [started]
    
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
              
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login docker.pkg.github.com --username "${DOCKER_USERNAME}" --password-stdin

# tsdk: Can add other architectures later on: --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
      - name: Docker Buildx (push)
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker buildx build \
            --secret id=package_key,src=${{ secrets.PACKAGE_KEY_ACTIONS }} \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --tag newchromantics/popnotpoker:latest \
            --file ./Dockerfile ./

      - name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery newchromantics/popnotpoker:latest 
      
      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
