name: Create Release

on:
  push:
    branches:
      - docker

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # setup node for npm packaging
      - name: Make github package
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      - name: Install Node Modules
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_KEY_ACTIONS }}" > .npmrc
          echo @newchromantics:registry=https://npm.pkg.github.com >> .npmrc
          npm install

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: newchromantics/popnotpoker/server
          tag_with_ref: true