name: Create Server Image

on:
  push:
    branches:
      - docker

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # setup node for npm packaging
      - name: Make github package
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      - name: Install Node Modules
        run: |
          echo "${DOCKER_PASSWORD}" | docker login docker.pkg.github.com --username "${DOCKER_USERNAME}" --password-stdin
      
      - name: Make npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_KEY_ACTIONS }}" > .npmrc
          echo @newchromantics:registry=https://npm.pkg.github.com >> .npmrc

# tsdk: Can add other architectures later on: --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
      - name: Docker Buildx (push)
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker buildx build \
          --secret id=npmrc,src=.npmrc \
          --platform linux/amd64 \
          --output "type=image,push=true" \
          --tag docker.pkg.github.com/newchromantics/popnotpoker/server:latest \
          .

      - name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery newchromantics/popnotpoker/server:latest
      
      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
